<div>
	<a href="/admin/logout">Cerrar sesion</a>
	<a href="/admin/listado">Listar productos</a>
</div>
<div>
	<form action="" method="POST">
		<p>Nombre <input type="text" name="nombre" /></p>
		<p>Descripcion <input type="text" name="descripcion" /></p>
		<p>Tipo 
			<select name="tipo">
				<option value="estandar">Estandar</option>
				<option value="amedida">A medida</option>
			</select>
		</p>
		<p>Stock <input type="text" name="stock" /></p>
		<p>Estado <input type="checkbox" name="estado" /></p>
		<input type="submit" value="Guardar" />
	</form>
</div>
