<div>
	<a href="/admin/logout">Cerrar sesion</a>
	<a href="/admin/listado">Listar productos</a>
</div>
<div>
	<form action="" method="POST">
	<p>Nombre <input type="text" name="nombre" value="<?php echo $this->producto['nombre']; ?>"/></p>
		<p>Descripcion <input type="text" name="descripcion" value="<?php echo $this->producto['descripcion']; ?>" /></p>
		<p>Tipo 
			<select name="tipo">
			<option value="estandar" <?php if($this->producto['tipo']=='estandar'){ ?>selected="selected" <?php } ?>>Estandar</option>
				<option value="amedida" <?php if($this->producto['tipo']=='amedida'){ ?>selected="selected" <?php } ?>>A medida</option>
			</select>
		</p>
		<p>Stock <input type="text" name="stock" value="<?php echo $this->producto['stock']; ?>" /></p>
		<p>Estado <input type="checkbox" name="estado" <?php if($this->producto['estado']){ ?> checked="checked" <?php } ?> /></p>
		<input type="submit" value="Guardar" />
	</form>
</div>
